---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        -
          image: postgres
          name: postgres
